# Generated by Django 5.0.1 on 2024-01-14 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorevent',
            name='work_order_pin_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_events', to='work_orders.workorder'),
        ),
    ]
