# Generated by Django 5.0.1 on 2024-01-16 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_alter_doorevent_work_order_pin_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorevent',
            name='actual_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
